version: 1
formatters:
  simple:
    format: '%(asctime)s - [%(levelname)s] %(message)s'
    datefmt: '%d/%m/%Y %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: logs/main_app.log
loggers:
  main_app:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: INFO
  handlers: [console]