version: 1
emoticons:
  smile_cat: ":smile_cat:"
  pouting_cat: ":pouting_cat:"
  kissing_cat: ":kissing_cat:"
  crying_cat: ":crying_cat_face:"
messages:
  add_success: "Item(ns) adicionado(s)! **PURR** "
  remove_success: "O item foi removido com sucesso! **PURR** "
  invalid_format_error: "O formato do(s) item(ns) enviado(s) é inválido! **MEOW** "
  multiple_items: "Caso queira enviar mais de 1 item, utilize `,` para separar os itens."
  single_item: "Apenas um item deve ser enviado por vez."
  empty_list: "Ainda não há itens nesta lista! "
  greetings: "Olá, %s! Segura a lista de comandos! Adicione sempre `&` após o comando! **MEOW** "
  duplicate_items: "O(s) item(ns) **%s** já está(ão) na lista e não foi(ram) adicionado(s)! Os demais foram adicionados com sucesso! **PURR** "
  usage_tips: "Adicionar permite múltiplos itens, enquanto remover apenas permite um único valor!"
commands:
  movie-list: "`-movies-list` - Lista de filmes a serem adicionados"
  series-list: "`-series-list` - Lista de séries a serem adicionadas"
  animes-list: "`-animes-list` - Lista de animes a serem adicionados"
  avaiable-libraries: "`-avaiable-libraries` - Lista as bibliotecas de mídia disponíveis no servidor"
  avaiable-movies: "`-avaiable-movies` - Lista os filmes disponíveis no servidor"
  avaiable-animes: "`-avaiable-animes` - Lista os animes disponíveis no servidor"
  avaiable-series: "`-avaiable-series` - Lista as séries disponíveis no servidor"
  avaiable-courses: "`-avaiable-courses` - Lista os cursos disponíveis no servidor"
  avaiable-animated-series: "`-avaiable-animated-series` - Lista os desenhos animados disponíveis no servidor"
  add-movies: "`-add-movies` - Adiciona filmes à lista."
  add-series: "`-add-series` - Adiciona series à lista."
  add-animes: "`-add-animes` - Adiciona animes à lista."
  remove-movies: "`-remove-movies` - Remove filmes da lista."
  remove-series: "`-remove-series` - Remove series da lista."
  remove-animes: "`-remove-animes` - Remove animes da lista."
